name: esamek
favicon: null
layout_spectrum: 0.6839
typography_spectrum: 0.66226
title: "Evan Samek's Grid.io Experimentation"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#15141c'
    - '#a37733'
    - '#0c425f'
    - '#a8a7aa'
  brandStrength: 0.8125
  lightness: 0.8125
  saturation: 0.6875
  rhythmicContrast: 0.75
purpose: []
